### ISSUE TITLE
Your Heroku App has stopped working.

### ISSUE THREAD

**Issue by 06ketan** [Ali-hd/Twitter-Clone#12]
Your Heroku App has stopped working.

In console, Status Code 503 is printed

![image](https://user-images.githubusercontent.com/57368152/181719902-3221c56f-9fe9-4789-8045-90961ee003cb.png)

**Comment by Ali-hd** [comment]
Please use the correct link for website 
https://twitterapp-clone.netlify.app/
or API link which is 
https://twitter-c-api.herokuapp.com
